UnShareFile:
  handler: lambda/UnShareFile/index.handler
  description: "UnShare File for a given wallet ID and file ID"
  memorySize: 512
  timeout: 5
  environment:
    TABLE_NAME_STORAGE_DATA: ${self:custom.dynamodb.StorageDataTable.name}
  events:
    - http:
        path: wallets/{wId}/storage/files/{fileId}/unshare
        method: post
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
      Resource:
        - ${self:custom.dynamodb.StorageDataTable.arn}
        - ${self:custom.dynamodb.StorageDataTable.arn}/*
