Resources:
  StorageServiceTable:
    DeletionPolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: near-storage
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: pk1
          AttributeType: S
        - AttributeName: sk1
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: pk1
              KeyType: HASH
            - AttributeName: sk1
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
