Resources:
  StorageServiceFilesBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: storage-service-files-${self:provider.stage}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - PUT
              - GET
              - HEAD
            AllowedHeaders:
              - '*'
            ExposedHeaders:
              - 'ETag'

  StorageServiceFilesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorageServiceFilesBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${StorageServiceFilesBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${StorageServiceOriginAccessIdentity}
