GetFile:
  handler: lambda/GetFile/index.handler
  description: 'Get a file based on wallet ID and file ID'
  memorySize: 128
  timeout: 5
  environment:
    TABLE_NAME_STORAGE_DATA: ${self:custom.dynamodb.StorageDataTable.name}
    SECRET_ARN_CLOUDFRONT_CDN_SIGNING_KEY: ${self:custom.secretsManager.CloudFrontCdnSigningKey.arn}
    CLOUDFRONT_URL: cdn.${self:provider.stage}.${self:custom.defaults.hostedZoneSuffix}
    REGION: ${self:provider.region}
  events:
    - http:
        path: /wallets/{wId}/storage/files/{fileId}
        method: get
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - ${self:custom.dynamodb.StorageDataTable.arn}
        - ${self:custom.dynamodb.StorageDataTable.arn}/*
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - ${self:custom.secretsManager.CloudFrontCdnSigningKey.arn}
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource:
        - ${self:custom.kms.DefaultKMS.arn} 