getFileStorage:
  handler: lambda/getFileStorage/index.handler
  description: "Allows user to retrieve a file details using the fileId"
  events:
    - httpApi:
        path: /wallets/{walletId}/storage/{fileId}
        method: get
        authorizer:
          type: request
          id: !ImportValue NearGatewayAuthorizerId
#    - http:
#        path: /wallets/{walletId}/files/{fileId}
#        method: get
#        authorizer:
#          name: ${self:service}-JWTAuthorizer
#          type: request
#          arn: ${ssm:/rest-service/lambda/JwtAuthorizer/arn}
  environment:
    # Avoid using Ref here as this may create a Circular dependency between resources https://go.aws/3pk3Nup
    ## TODO: use ${self:custom.startup-service.filesBucket.name} when # TODO: uncomment this section when https://github.com/nearcomponents/gateway/pull/14 is merged
    CLOUDFRONT_URL: ${self:custom.cdn.url.${self:provider.stage}}
    CLOUDFRONT_SECRET_NAME: ${self:custom.file-service.cloudfront.secret-name}
    BUCKET_NAME_FILES: ${self:custom.file-service.s3.storage.name}
    TABLE_NAME_FILES: ${self:custom.file-service.dynamodb.files.name}
    ## TODO: use ${ssm:/dynamodb/wallet-service/wallets/name} when exported by Terraform
    TABLE_NAME_WALLETS: near-wallets
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        ## TODO: use ${ssm:/dynamodb/wallet-service/wallets/arn} when exported by Terraform
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-wallets
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - ${self:custom.file-service.dynamodb.files.arn}
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - ${self:custom.file-service.s3.storage.arn}
        - ${self:custom.file-service.s3.storage.arn}/*
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:/storage-service/cloudfront/signers*

