updateFile:
  handler: lambda/updateFile/index.handler
  description: "Allows updating a file"
  events:
    - httpApi:
        path: /wallets/{walletId}/storage/{fileId}
        method: put
        authorizer:
          type: request
          id: !ImportValue NearGatewayAuthorizerId
    - httpApi:
        path: /wallets/{walletId}/files/{fileId}
        method: put
        authorizer:
          type: request
          id: !ImportValue NearGatewayAuthorizerId
  #    - http:
  #        path: /wallets/{walletId}/files/{fileId}
  #        method: put
  #        authorizer:
  #          name: ${self:service}-JWTAuthorizer
  #          type: request
  #          arn: ${ssm:/rest-service/lambda/JwtAuthorizer/arn}
  environment:
    BUCKET_NAME_FILES: ${self:custom.file-service.s3.storage.name}
    TABLE_NAME_FILES: ${self:custom.file-service.dynamodb.files.name}
    CLOUDFRONT_SECRET_NAME: ${self:custom.file-service.cloudfront.secret-name}
    CLOUDFRONT_URL: ${self:custom.cdn.url.${self:provider.stage}}
    TABLE_NAME_WALLETS: near-wallets
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.file-service.dynamodb.files.arn}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.file-service.dynamodb.storage.arn}
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        ## TODO: use ${ssm:/dynamodb/wallet-service/wallets/arn} when exported by Terraform
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-wallets
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-files
    - Effect: Allow
      Action:
        - s3:*
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:AbortMultipartUpload
      Resource:
        - ${self:custom.file-service.s3.storage.arn}/*
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:/storage-service/cloudfront/signers*
