fetchFoldersList:
  handler: lambda/fetchFoldersList/index.handler
  description: "Initiate file creation by generating a pre-signed S3 URL"
  events:
    - httpApi:
        path: /wallets/{walletId}/storage/folders/list
        method: get
        authorizer:
          type: request
          id: !ImportValue NearGatewayAuthorizerId
  environment:
    TABLE_NAME_FOLDERS: near-storage
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-wallets
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - ${self:custom.file-service.dynamodb.files.arn}
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:AbortMultipartUpload
      Resource:
        - Fn::Join: ["/", [!ImportValue FileServiceFilesBucketArn, "*"]]
