removeItems:
  handler: lambda/removeItems/index.handler
  description: "Initiate file creation by generating a pre-signed S3 URL"
  events:
    - stream:
        type: dynamodb
        batchSize: 1
        startingPosition: LATEST
        arn: ${self:custom.file-service.dynamodb.storage.streamArn}
        filterPatterns:
          ## Folder was successfully deleted
          - eventName: [REMOVE]
  environment:
    TABLE_NAME_FOLDERS: near-storage
    TABLE_NAME_WALLETS: near-wallets
    TABLE_NAME_FILES: near-files
    iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-wallets
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - ${self:custom.file-service.dynamodb.files.arn}
        - ${self:custom.file-service.dynamodb.files.arn}/index/*
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - ${self:custom.file-service.dynamodb.storage.arn}
        - ${self:custom.file-service.dynamodb.storage.arn}/index/*
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:AbortMultipartUpload
      Resource:
        - Fn::Join: ["/", [!ImportValue FileServiceFilesBucketArn, "*"]]
