listFiles:
  handler: lambda/listFiles/index.handler
  description: "Allows retrieving all the user files"
  events:
    - httpApi:
        path: /wallets/{walletId}/files
        method: get
        authorizer:
          type: request
          id: !ImportValue NearGatewayAuthorizerId
#    - http:
#        path: /wallets/{walletId}/files
#        method: get
#        authorizer:
#          name: ${self:service}-JWTAuthorizer
#          type: request
#          arn: ${ssm:/rest-service/lambda/JwtAuthorizer/arn}
  environment:
    TABLE_NAME_FILES: ${self:custom.file-service.dynamodb.files.name}
    ## TODO: use ${ssm:/dynamodb/wallet-service/wallets/name} when exported by Terraform
    TABLE_NAME_WALLETS: near-wallets
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        ## TODO: use ${ssm:/dynamodb/wallet-service/wallets/arn} when exported by Terraform
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-wallets
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - ${self:custom.file-service.dynamodb.files.arn}
