verify-wallet:
  handler: lambda/verify-wallet/index.handler
  description: "Verify wallet"
  events:
    - httpApi:
        path: /wallets/verify/{walletId}
        method: GET
#    - http:
#        path: /wallets/verify/{walletId}
#        method: GET
#        authorizer:
#          name: ${self:service}-JWTAuthorizer
#          type: request
#          arn: ${ssm:/rest-service/lambda/JwtAuthorizer/arn}
  environment:
    TABLE_NAME_WALLETS: near-wallets
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-wallets
