ListChildrenFiles:
  handler: lambda/ListChildrenFiles/index.handler
  description: "List all children files for a given wallet ID and Folder Id"
  memorySize: 512
  timeout: 5
  environment:
    TABLE_NAME_STORAGE_DATA: ${self:custom.dynamodb.StorageDataTable.name}
  events:
    - http:
        path: wallets/{wId}/storage/folders/{folderId}/files
        method: get
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - ${self:custom.dynamodb.StorageDataTable.arn}
        - ${self:custom.dynamodb.StorageDataTable.arn}/*
