shareFolder:
  handler: lambda/shareFolder/index.handler
  description: 'Share a folder with a list of receivers'
  events:
    - httpApi:
        path: /wallets/{walletId}/storage/folders/{folderId}/share
        method: post
        authorizer:
          type: request
          id: !ImportValue NearGatewayAuthorizerId
  environment:
    TABLE_NAME_FOLDERS: ${ssm:/file-service/dynamodb/storage/name}
    TABLE_NAME_WALLETS: ${ssm:/wallet-service/dynamodb/wallets/name}
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - ${self:custom.file-service.dynamodb.wallets.arn}
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - ${self:custom.file-service.dynamodb.storage.arn}
